version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/client_werifydb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/var/lib/mongo
    ports:
      - "27017:27017"
    command: ["--config", "/etc/mongo/mongod.conf"]
    
volumes:
  mongo_data:
