version: '3'
services:
  web:
    build:
      context: .
      target: production
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/client_werifydb
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
