version: '3.8'
services:
  web:
    build:
      context: .
      target: production
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
