services:
  web:
    build:
      context: .
      target: production
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
